/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.gc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.gc.ui.AbstractGcUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GcUiModule extends AbstractGcUiModule {
  public GcUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
