/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.example.statemachine.ui.internal.StatemachineActivator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return StatemachineActivator.getInstance().getInjector("org.xtext.example.mydsl.MyDsl");
	}

}
