/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.gc.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.xtext.example.gc.ide.contentassist.antlr.internal.InternalGcParser;
import org.xtext.example.gc.services.GcGrammarAccess;

public class GcParser extends AbstractContentAssistParser {

	@Inject
	private GcGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalGcParser createParser() {
		InternalGcParser result = new InternalGcParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getPositionAccess().getAlternatives(), "rule__Position__Alternatives");
					put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
					put(grammarAccess.getModelAccess().getConditionsAssignment(), "rule__Model__ConditionsAssignment");
					put(grammarAccess.getConditionAccess().getConditionAssignment_1(), "rule__Condition__ConditionAssignment_1");
					put(grammarAccess.getConditionAccess().getPositionAssignment_3(), "rule__Condition__PositionAssignment_3");
					put(grammarAccess.getConditionAccess().getEventAssignment_5(), "rule__Condition__EventAssignment_5");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalGcParser typedParser = (InternalGcParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GcGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GcGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
