/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.gc.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.gc.ui.internal.GcActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GcExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GcActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GcActivator.getInstance().getInjector(GcActivator.ORG_XTEXT_EXAMPLE_GC_GC);
	}
	
}
