/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.gc.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.gc.parser.antlr.internal.InternalGcParser;
import org.xtext.example.gc.services.GcGrammarAccess;

public class GcParser extends AbstractAntlrParser {

	@Inject
	private GcGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGcParser createParser(XtextTokenStream stream) {
		return new InternalGcParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public GcGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GcGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
