/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.gc.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class GcUiModule extends AbstractGcUiModule {
}
