/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.gc


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GcRuntimeModule extends AbstractGcRuntimeModule {
}
