/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.gc.validation;

import org.xtext.example.gc.validation.AbstractGcValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GcValidator extends AbstractGcValidator {
}
