/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.gc.gc;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.gc.gc.Condition#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.xtext.example.gc.gc.Condition#getPosition <em>Position</em>}</li>
 *   <li>{@link org.xtext.example.gc.gc.Condition#getEvent <em>Event</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.gc.gc.GcPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
  /**
	 * Returns the value of the '<em><b>Condition</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Condition</em>' attribute.
	 * @see #setCondition(String)
	 * @see org.xtext.example.gc.gc.GcPackage#getCondition_Condition()
	 * @model
	 * @generated
	 */
  String getCondition();

  /**
	 * Sets the value of the '{@link org.xtext.example.gc.gc.Condition#getCondition <em>Condition</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Condition</em>' attribute.
	 * @see #getCondition()
	 * @generated
	 */
  void setCondition(String value);

  /**
	 * Returns the value of the '<em><b>Position</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Position</em>' attribute.
	 * @see #setPosition(String)
	 * @see org.xtext.example.gc.gc.GcPackage#getCondition_Position()
	 * @model
	 * @generated
	 */
  String getPosition();

  /**
	 * Sets the value of the '{@link org.xtext.example.gc.gc.Condition#getPosition <em>Position</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Position</em>' attribute.
	 * @see #getPosition()
	 * @generated
	 */
  void setPosition(String value);

  /**
	 * Returns the value of the '<em><b>Event</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Event</em>' attribute.
	 * @see #setEvent(String)
	 * @see org.xtext.example.gc.gc.GcPackage#getCondition_Event()
	 * @model
	 * @generated
	 */
  String getEvent();

  /**
	 * Sets the value of the '{@link org.xtext.example.gc.gc.Condition#getEvent <em>Event</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Event</em>' attribute.
	 * @see #getEvent()
	 * @generated
	 */
  void setEvent(String value);

} // Condition
