/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.gc.gc;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.gc.gc.GcFactory
 * @model kind="package"
 * @generated
 */
public interface GcPackage extends EPackage
{
  /**
	 * The package name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNAME = "gc";

  /**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_URI = "http://www.xtext.org/example/gc/Gc";

  /**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_PREFIX = "gc";

  /**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  GcPackage eINSTANCE = org.xtext.example.gc.gc.impl.GcPackageImpl.init();

  /**
	 * The meta object id for the '{@link org.xtext.example.gc.gc.impl.ModelImpl <em>Model</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.example.gc.gc.impl.ModelImpl
	 * @see org.xtext.example.gc.gc.impl.GcPackageImpl#getModel()
	 * @generated
	 */
  int MODEL = 0;

  /**
	 * The feature id for the '<em><b>Conditions</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int MODEL__CONDITIONS = 0;

  /**
	 * The number of structural features of the '<em>Model</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int MODEL_FEATURE_COUNT = 1;

  /**
	 * The meta object id for the '{@link org.xtext.example.gc.gc.impl.ConditionImpl <em>Condition</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.example.gc.gc.impl.ConditionImpl
	 * @see org.xtext.example.gc.gc.impl.GcPackageImpl#getCondition()
	 * @generated
	 */
  int CONDITION = 1;

  /**
	 * The feature id for the '<em><b>Condition</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int CONDITION__CONDITION = 0;

  /**
	 * The feature id for the '<em><b>Position</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int CONDITION__POSITION = 1;

  /**
	 * The feature id for the '<em><b>Event</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int CONDITION__EVENT = 2;

  /**
	 * The number of structural features of the '<em>Condition</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int CONDITION_FEATURE_COUNT = 3;


  /**
	 * Returns the meta object for class '{@link org.xtext.example.gc.gc.Model <em>Model</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Model</em>'.
	 * @see org.xtext.example.gc.gc.Model
	 * @generated
	 */
  EClass getModel();

  /**
	 * Returns the meta object for the containment reference list '{@link org.xtext.example.gc.gc.Model#getConditions <em>Conditions</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Conditions</em>'.
	 * @see org.xtext.example.gc.gc.Model#getConditions()
	 * @see #getModel()
	 * @generated
	 */
  EReference getModel_Conditions();

  /**
	 * Returns the meta object for class '{@link org.xtext.example.gc.gc.Condition <em>Condition</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Condition</em>'.
	 * @see org.xtext.example.gc.gc.Condition
	 * @generated
	 */
  EClass getCondition();

  /**
	 * Returns the meta object for the attribute '{@link org.xtext.example.gc.gc.Condition#getCondition <em>Condition</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Condition</em>'.
	 * @see org.xtext.example.gc.gc.Condition#getCondition()
	 * @see #getCondition()
	 * @generated
	 */
  EAttribute getCondition_Condition();

  /**
	 * Returns the meta object for the attribute '{@link org.xtext.example.gc.gc.Condition#getPosition <em>Position</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Position</em>'.
	 * @see org.xtext.example.gc.gc.Condition#getPosition()
	 * @see #getCondition()
	 * @generated
	 */
  EAttribute getCondition_Position();

  /**
	 * Returns the meta object for the attribute '{@link org.xtext.example.gc.gc.Condition#getEvent <em>Event</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Event</em>'.
	 * @see org.xtext.example.gc.gc.Condition#getEvent()
	 * @see #getCondition()
	 * @generated
	 */
  EAttribute getCondition_Event();

  /**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
  GcFactory getGcFactory();

  /**
	 * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
	 * @generated
	 */
  interface Literals
  {
    /**
		 * The meta object literal for the '{@link org.xtext.example.gc.gc.impl.ModelImpl <em>Model</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.example.gc.gc.impl.ModelImpl
		 * @see org.xtext.example.gc.gc.impl.GcPackageImpl#getModel()
		 * @generated
		 */
    EClass MODEL = eINSTANCE.getModel();

    /**
		 * The meta object literal for the '<em><b>Conditions</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference MODEL__CONDITIONS = eINSTANCE.getModel_Conditions();

    /**
		 * The meta object literal for the '{@link org.xtext.example.gc.gc.impl.ConditionImpl <em>Condition</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.example.gc.gc.impl.ConditionImpl
		 * @see org.xtext.example.gc.gc.impl.GcPackageImpl#getCondition()
		 * @generated
		 */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
		 * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute CONDITION__CONDITION = eINSTANCE.getCondition_Condition();

    /**
		 * The meta object literal for the '<em><b>Position</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute CONDITION__POSITION = eINSTANCE.getCondition_Position();

    /**
		 * The meta object literal for the '<em><b>Event</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute CONDITION__EVENT = eINSTANCE.getCondition_Event();

  }

} //GcPackage
