/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.gc.gc;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.gc.gc.Model#getConditions <em>Conditions</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.gc.gc.GcPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
	 * Returns the value of the '<em><b>Conditions</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.example.gc.gc.Condition}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Conditions</em>' containment reference list.
	 * @see org.xtext.example.gc.gc.GcPackage#getModel_Conditions()
	 * @model containment="true"
	 * @generated
	 */
  EList<Condition> getConditions();

} // Model
