/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.gc.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.example.gc.ui.internal.GcActivator;

public class GcUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GcActivator.getInstance().getInjector("org.xtext.example.gc.Gc");
	}

}
