/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.gc;

import org.xtext.example.gc.AbstractGcRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GcRuntimeModule extends AbstractGcRuntimeModule {
}
