/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.gc;

import org.xtext.example.gc.GcStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GcStandaloneSetup extends GcStandaloneSetupGenerated {
  public static void doSetup() {
    GcStandaloneSetup _gcStandaloneSetup = new GcStandaloneSetup();
    _gcStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
